export const SET_QUIZES = 'quiz/SET_QUIZES'
export const SET_QUIZ = 'quiz/SET_QUIZ'
export const SET_GRADE = 'quiz/SET_GRADE'
export const SET_QUESTIONS = 'quiz/SET_QUESTIONS'
export const SET_QUESTION = 'quiz/SET_QUESTION'
